zuul:
  #全部服务忽略敏感头（全部服务都可传递cookie）
  sensitive-headers: 
  routes:
# /myProduct1/product/list  ->  /product/product/list
    myroute1:
      path: /myProduct1/**
      serviceId: product
# not filter cookie
      sensitiveHeaders:
# simple
#    product: /myProduct2/**
  ignored-patterns:
    - /**/product/listForOrder
#    - /product/product/listForOrder
#    - /myProduct/product/listForOrder
spring:
  redis:
    host: 192.168.1.76
    port: 6379
management:
  security:
    enabled: false
