spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: aA111111
    url: jdbc:mysql://192.168.1.76:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.76
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.1.76
    port: 6379
  zipkin:
    base-url: http://192.168.1.76:9411/
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1
env:
  dev
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
#  instance:
#    prefer-ip-address: true
girl:
  name: lili
  age: 19
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic
