spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: aA111111
    url: jdbc:mysql://192.168.1.76:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.76
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.76:8761/eureka,http://192.168.1.76:8762/eureka,http://192.168.1.76:8763/eureka
env:
 dev
girl:
  name: lili
  age: 19
